#cloud-config

  # Install .NET Runtime 8.0
  - apt-get update
  - apt-get install -y aspnetcore-runtime-8.0

  # Create application directory (if not already created)
  - mkdir -p /opt/CloudSoft
  - chown -R www-data:www-data /opt/CloudSoft

  # Reload systemd and start service
  - systemctl daemon-reload
  - systemctl enable CloudSoft.service
  - systemctl start CloudSoft.service

# Create a service for the application
write_files:
  - path: /etc/systemd/system/CloudSoft.service
    content: |
      [Unit]
      Description=ASP.NET Web App running on Ubuntu
      After=network.target

      [Service]
      WorkingDirectory=/opt/CloudSoft
      ExecStart=/usr/bin/dotnet /opt/CloudSoft/CloudSoft.dll
      Restart=always
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=CloudSoft
      User=www-data
      Group=www-data
      Environment=ASPNETCORE_ENVIRONMENT=Production
      Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
      Environment="ASPNETCORE_URLS=http://*:5000"

      [Install]
      WantedBy=multi-user.target      
    owner: root:root
    permissions: '0644'

systemd:
  units:
    - name: CloudSoft.service
      enabled: true